Attempt to fix a random "Comparison method violates its general contract"
We assume that compareTo is consistent with equal but may not be
transitive so we simplify it.

     Exception in thread "AWT-EventQueue-0"
java.lang.IllegalArgumentException: Comparison method violates its
general contract!

at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:835)
at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:453)
at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:376)
at java.util.ComparableTimSort.sort(ComparableTimSort.java:182)
at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
at java.util.Arrays.sort(Arrays.java:472)
at javax.swing.DefaultRowSorter.sort(DefaultRowSorter.java:607)
at javax.swing.DefaultRowSorter.setSortKeys(DefaultRowSorter.java:319)
at
org.jdesktop.swingx.sort.DefaultSortController.setSortOrder(DefaultSortController.java:187)
at org.jdesktop.swingx.JXTable.setSortOrder(JXTable.java:1881)
at
org.jajuk.ui.views.AbstractTableView.initTable(AbstractTableView.java:763)
at org.jajuk.ui.views.WebRadioView.shortCall(WebRadioView.java:209)